version: '3'
services:
    nginx:
        image: nginx:1.9
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - autofeed
        restart: unless-stopped
    autofeed:
        build: ./
        restart: unless-stopped
